name: HPhi
description: AFH chain

platform:
  system:  ohtaka
  queue:   i8cpu
  node:    8
  elapsed: 00:30:00

prologue:
  code: |
    echo "start"
    date
    module purge
    module load oneapi_compiler/2023.0.0 openmpi/4.1.5-oneapi-2023.0.0-classic

    ulimit -s unlimited

    source ~/env/conda.sh
    conda activate htptools

    source /home/issp/materiapps/oneapi_compiler_classic-2023.0.0--openmpi-4.1.5/parallel/parallelvars-20210622-1.sh
    source /home/issp/materiapps/oneapi_compiler_classic-2023.0.0--openmpi-4.1.5/hphi/hphivars.sh

    # Option to use dual rail
    #export MPI_IB_RAILS=2

    #MKL_DEBUG_CPU_TYPE=5
    ulimit -s unlimited
    export KMP_STACKSIZE=512m
    export UCX_TLS='self,sm,ud'

epilogue:
  code: |
    sh ./extract_gap.sh
    echo "done"
    date

jobs:
  hphi:
    description: run HPhi
    node: [2,8,32]
    # node: [3,6,64]
    run: |
      srun HPhi -s stan.in 2>&1 | tee stdout
      cat output/zvo_energy.dat | \
        awk 'BEGIN {gs="inf"}
             $1 = /Energy/ {if(gs=="inf") {gs=$2} else {exct=$2}}
             END {print exct-gs }' > gap.dat
